steps:
  - label: ":github: Fetch Dockerfile"
    commands:
      - git clone https://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@github.com/loki-4321/Nodejs.git /tmp/Nodejs
      - cp /tmp/Nodejs/Dockerfile .
      - rm -rf /tmp/Nodejs

  - label: ":docker: Push to AWS ECR"
    plugins:
      - seek-jobs/gantry#v2.0.0:
          command: gantry build --file containerImage.yaml --region ap-southeast-2
          #environment: <%- devGantryEnvironmentName %>
          file: containerImage.yaml
          #region: <%- region %>
          #values:
           # - .gantry/common.yml
           # - .gantry/dev.yml
          env:
            GITHUB_TOKEN: "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"
  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build

  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":package: Package"
    command: tests.sh
    artifact_paths: "pkg/*"
    
  - label: ":hammer: Example Script"
    command: "tests.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
