agents:
  queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
steps:
  - label: ":github: Fetch Dockerfile"
    commands:
      - git clone https://github.com/loki-4321/Nodejs.git /tmp/Nodejs
      - cp /tmp/Nodejs/Dockerfile .
      - rm -rf /tmp/Nodejs
  - label: 📦 Build & Package
    plugins:
      - seek-jobs/gantry#<gantry_version>:
          command: build
          file: containerImage.yaml
          region: us-east-1
  - wait
  - label: 🚀 Deploy
    plugins:
      - seek-jobs/gantry#<gantry_version>:
          command: apply
          environment: dev
          file: service.yaml
          region: us-east-1
        
