steps:
  - label: ":github: Fetch Dockerfile"
    commands:
      - git clone https://github.com/loki-4321/Nodejs.git /tmp/Nodejs
      - cp /tmp/Nodejs/Dockerfile .
      - rm -rf /tmp/Nodejs

  - label: ":docker: Build Docker Images"
    plugins:
      - docker#v3.7.0:
          image: "docker:23"
          always_pull: true
          environment:
            - DOCKER_BUILDKIT=1
  - label: ":docker: Build Docker Image"
    commands:
      - docker build -t dockerssh-image .
    commands:
      - export AWS_REGION=us-east-1 
      - aws configure set region $AWS_REGION
      - $(aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws/t7l5b0q1)
      - docker build -t myrepobuildkite . 
      - docker tag myrepobuildkite:latest public.ecr.aws/t7l5b0q1/myrepobuildkite:latest
      - docker push public.ecr.aws/t7l5b0q1/myrepobuildkite:latest
  - label: ":cloudformation: Deploy Stack"
    commands:
      - aws cloudformation deploy --stack-name Lokeshstac --template-file .buildkite/cf.yml --region us-east-1 
  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build

  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":package: Package"
    command: tests.sh
    artifact_paths: "pkg/*"
    
  - label: ":hammer: Example Script"
    command: "tests.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
