steps:
  - label: ":github: Fetch Dockerfile"
    commands:
      - git clone https://github.com/loki-4321/Nodejs.git /tmp/Nodejs
      - cp /tmp/Nodejs/Dockerfile .
      - rm -rf /tmp/Nodejs

  - label: ":docker: Build Docker Image"
    commands:
      - docker build -t dockerss-image .

  - label: ":docker: Push to AWS ECR"
    plugins:
      - docker#v3.7.0:
          login: true
          build: .
          repository: 296281347850.dkr.ecr.us-east-1.amazonaws.com/Nodejs
          tags: latest:v2
    env:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build

  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":package: Package"
    command: tests.sh
    artifact_paths: "pkg/*"
    
  - label: ":hammer: Example Script"
    command: "tests.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
