steps:
  - label: ":github: Fetch Dockerfile"
    commands:
      - git clone https://github.com/loki-4321/Nodejs.git /tmp/Nodejs
      - cp /tmp/Nodejs/Dockerfile .
      - rm -rf /tmp/Nodejs

  - label: ":docker: Build Docker Image"
    plugins:
      - docker#v3.7.0:
          login: true
          image: my-dockerss-image:v1
    commands:
      - docker build -t dockerss-image .
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t7l5b0q1
      - docker build -t myrepobuildkite . 
      - docker tag myrepobuildkite:latest public.ecr.aws/t7l5b0q1/myrepobuildkite:latest
      - docker push public.ecr.aws/t7l5b0q1/myrepobuildkite:latest
  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build

  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":package: Package"
    command: tests.sh
    artifact_paths: "pkg/*"
    
  - label: ":hammer: Example Script"
    command: "tests.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
