steps:
  - label: "Login to AWS ECR"
    plugins:
      - docker-compose#3.0.0:  # Replace with the actual plugin version
          build: "/root/dockerfile/Dockerfile"  # Specify the path to your Dockerfile
          tag: "lokesh:latest"
    key: "docker-login"

  

agents:
  queue: "default"


  #############################
  agents:
  queue: <queue>
steps:
  - label: 📦 Build & Package
    plugins:
      - seek-jobs/gantry#v1.7.0:
          command: build
          file: <gantry-container-image-file>
          region: <region>
  - wait
  - label: 🚀 Deploy
    plugins:
      - seek-jobs/gantry#v1.7.0:
          command: apply
          environment: <environment>
          file: <gantry-service-file>
          region: <region>
