agents:
  queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

configs:
  plugins:
    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.0.0:
        cache-on:
          - package.json
          - yarn.lock
        dockerfile: Dockerfile
        #secrets: id=npm,src=.npmrc

    - &private-npm
      seek-oss/private-npm#v1.2.0:
        env: NPM_READ_TOKEN

steps:
  - label: 🧖‍♀️ Warm Prod
    command: ':'
    key: warm-prod
    plugins:
      - *private-npm
      - *docker-ecr-cache

  - label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test:ci'
      - yarn test:ci
      - echo '--- yarn lint'
      - yarn lint
    depends_on: warm-prod
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - *private-npm
      - *docker-ecr-cache
      - docker-compose#v4.12.0:
          run: app
    timeout_in_minutes: 10

  - label: 📦 Build & Package
    depends_on: warm-prod
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - seek-jobs/gantry#v2.0.0:
          command: build
          file: gantrybuild.yml
          region: <%- region %>
          values: .gantry/values-dev.yml
